### ISSUE TITLE
Feature: User can create an item.

### ISSUE THREAD

**Issue by mioriimai** [mioriimai/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 User can create an item.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

As creating an item, user can upload an image of the item, add the category(drop down menu), add brand(drop down menu), add color(multiple select), and add note.
In the uploading an image process, use API (https://www.remove.bg/api#remove-background) to remove the background of the image and shows the image that the background was removed to the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/54726911/210013813-5e3817c0-a038-4770-aef0-6ae669617322.png)

![image](https://user-images.githubusercontent.com/54726911/210013641-aecd55ff-168b-4cb0-b522-87202ca6946b.png)

![image](https://user-images.githubusercontent.com/54726911/210013592-f5a0676b-ef38-4123-ad31-201abe760c5c.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Import tables from database designer into `schema.sql`.
- [x] Add a dummy date to the users table inside of `data.sql`.
- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ... insert a new item into the items table.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... send a POST request to create new item into the items table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a new conponent named `app-context.js` in lib directory.
  - [x] Import React from 'react'.
  - [x] Assign createContext function of React object with no argument  to constant variable `AppContext`.
  - [x] Export default AppContext.
- [x] Create new component named `navber.jsx`.
  - [x] Import React and AppContext.
  - [x] Add a class `Navber` in `navber.jsx`.
  - [x] In the class, fill the render function.
  - [x] Check that the navbar looks good on both mobile and desktop screens.
  - [x] Add `Navbar.concextType = AppContext` at the bottom of the file.
- [x] Create new component named `app-drawer.jsx`.
  - [x] Add a class `AppDrawer` in the file.
  - [x] Add constructor, super, state.
  - [x] Add handleMenuIconClick function.
  - [x] Add handleLinksOrShadeClick function.
  - [x] Fill render function.
  - [x] Check that the it looks good on both mobile and desktop screens.
  - [x] Add <AppDrawer /> in Navbar.
- [x] Create new component named `home-view.jsx`.
  - [x] Add a new class HomeView to the component.
  - [x] Fill the render function.
  - [x] Check that the it looks good on both mobile and desktop screens.
- [x] Add constructor in App component.
- [x] Add componentDidMount function in App component.
- [x] Add renderPage function to make it able to do view-swapping. 
- [x] Create new component named `form-item.jsx`.
- [x] Create new component named `item-view.jsx`.
  - [x] Add a class `Itemview` to the component.
  - [x] Add constructor and super and this.state.
  - [x] Add handleImageChange function.
  - [x] Add handleCategoryChange function.
  - [x] Add handleBrandChange function.
  - [x] Add handleColorChange function.
  - [x] Add handleNoteChange function.
  - [x] Add handleSubmit function.
    - [x] Add fecth to post the user inputs in database.
  - [x] Add a confirmation pop up window.
  - [x] Make sure every things looks okay on both mobile and desktop screens.
  - [x] Fill the render function.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
