### ISSUE TITLE
Feature: User can delete an outfit. 

### ISSUE THREAD

**Issue by mioriimai** [mioriimai/final-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete an outfit. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the edit outfit view, there is a delete icon at the left down corner. By clicking it, a popup windon shows up asking are you sure to delete the outfit. By clicking "delete" button, the outfit is removed from the list and it takes to the a list of outfit view.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/54726911/210016804-7840d9ad-56f1-4739-9711-df5e74e7cf5c.png)
![image](https://user-images.githubusercontent.com/54726911/210016833-30519580-ca35-4aef-a54c-722b92744dbc.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... ...send a DETELE request to delete the selected outfit from the outfits table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] In the edit-outfit component,
  - [x] Add deleteComfirm in the `this.state` and set it to false.
  - [x] Add a trash icon to the edit view.
  - [x] Create a new function called `handleDeleteConfirmPopupClick()` method .
    - [x] Set the deleteConfirm to false.
  - [x] Add a confirmation pop up window.
  - [x] Add onClick of handleDeleteConfirmPopup to the trash can icon annd the cancel button.
  - [x] Add handleDeleteOutfit() method.
    - [x] Use fetch to delete an outfit from outfits table and items from outfitItems table.
  - [x] Add onClick handleDeleteOutfit to the delete button and set the href to #outfits.
  - [x] Make sure clicking delete button takes user to the outfits view.
- [x] Check everything looks god on both mobile and desktop screen. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
