### ISSUE TITLE
Feature: User can add one of outfits to the favorite list.

### ISSUE THREAD

**Issue by mioriimai** [mioriimai/final-project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add one of outfits to the favorite list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the list of outfits view, when user mouse over on outfit, the heart icon shows up and by clicking it, the color of heart changes to pink and the outfit is added to the favorit list.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/54726911/210017130-98a1a637-c061-4170-8a0d-cdcd1dddaed8.png)

![image](https://user-images.githubusercontent.com/54726911/210017050-c0b4930e-9138-418a-a7a3-9848ccff48dd.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...to send a POST request to update an outfit's favorite status.
- [x] Test with HTTPie
- [x] Update `server/index.js` to ...to send a GET request to get outfit'data that has favorite=true.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] In items component...
  - [x] Add a heart icon to each outfit.
  - [x] Create a new function called handleFavoritesClick() method.
  - [x] In the handleFavoritesClick() method, use fetch to update the favorites state of an outfit. If it was true, change it to false(opposite to the previous state).
  - [x] Add onClick to the icon element.
- [x] In favorites component...
  - [x]  Fill the render() method for favorites out fit view.
  - [x] In componentDidMount(), use fetch to get outfits that have favorite=true.
  - [x] Update handleFavoriteClick() method to update favorite status of outfit.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
