### ISSUE TITLE
Feature: User can view a list of items.

### ISSUE THREAD

**Issue by mioriimai** [mioriimai/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of items.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

By clicking "See Items" button in home view or "Items" in navber, user can view a list of items they added.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/54726911/210014122-9209f6ae-cd2c-4517-8045-57cc0d67d8f8.png)
![image](https://user-images.githubusercontent.com/54726911/210014166-b93b3a42-eed5-4ff1-8750-401f3e953a7d.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to set a GET request to view the items.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] In `app.jsx` file, update the `renderPage() `function to make able to swap to the items view.
- [x] Create a new component named `list-view.jsx`.
  - [x] Import React from 'react'.
  - [x] Add `ListView` class in it.
  - [x] In the class, add `render()` function and add `<div>`.
- [x] Create a new component named `items.jsx`.
  - [x] Import React from 'react'.
  - [x] Add `Items` class in it.
  - [x] In the class, add `render()` function and add p tag with `this.props.content` and import Items from `items.jsx` and add List conponent in the `render()` function with `content="items"` in `list-view.jsx` to test if the props in `list-view.jsx` works fine.
  - [x] In `items.jsx`, add some dummy elements and style them to match the wireframe.
  - [x] Check that the it looks good on both mobile and desktop screens.
  - [x] Add `constructor()` function and super, this.state.
  - [x] Add componentDidMount() function.
    - [x] Add fetch to get the items data from the database.
  - [x] Add handleMouseEnter() function and handleMouseLeave() function to make it be able to hover on item and show notes.
  - [x] Add "Add Items" button and set the href to #add-item.
  - [x] Add handleAddItemsClick function and update state by using`this.setState`.
- [x] Add fetch to get the items data from the database.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
