### ISSUE TITLE
Feature: User can sign up.

### ISSUE THREAD

**Issue by mioriimai** [mioriimai/final-project#26]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
By clicking the user icon in the right top coner, it takes user to sigh in view. In the button, there is a sign up button, and by clicking the button, user sign up view shows up and user can sign up.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/54726911/224579075-dace73a8-a3d1-455b-ad5f-f08c51ee23d2.png)
![image](https://user-images.githubusercontent.com/54726911/224579093-744625ed-c8b4-42a0-a693-f99a12a83727.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...send a POST request for sign up.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Add a user icon to the navbar.
- [x] Update `renderPage()` method in `app.jsx`.
- [x] Add hash-password.js to create hasedPassword.
- [x] Create a new component called sign-up.
  - [x] Fill the render() method with form.
  - [x] Make sure it looks fine on both mobile and desktop.
  - [x] Add handleChangeInput() method.
  - [x] Add handleSubmit() method.
  - [x] Make sure the validation messages look good on both mobile and desktop.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
