### ISSUE TITLE
Feature: User can sign-in and sign-out.

### ISSUE THREAD

**Issue by mioriimai** [mioriimai/final-project#28]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

![image](https://user-images.githubusercontent.com/54726911/225491504-db4ba6b5-a7a8-4186-9a0a-6b97cb6c2cbf.png)
![image](https://user-images.githubusercontent.com/54726911/225491537-ed36720c-70eb-40b6-8853-c2c9d4b113f7.png)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Add `authorization-middleware.js`.
- [x] Update `server/index.js` to ... send a POST request to sign-in.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a new component called `sign-in`.
- [x] Update r`enderPage()` method for sign-in view in `app.jsx`.
- [x] In `sign-in.jsx`
  - [x]  Fill the render() method with the form.
  - [x] Make sure it looks good on both mobile and desktop.
  - [x] Add handleChangeUsername() method.
  - [x] Add handleChangePassword() method.
  - [x] Update `renderPage() function` in `app.jsx`.
  - [x] Add sign-out button.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
