### ISSUE TITLE
Feature: User can edit an item.

### ISSUE THREAD

**Issue by mioriimai** [mioriimai/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit an item.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user clicks the edit button in a list of items view, it takes to the edit item view and user can change the information.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/54726911/210014521-016e59fc-468f-4d50-86e1-b9d5b28648a7.png)
![image](https://user-images.githubusercontent.com/54726911/210014578-7f194928-7b37-4896-a8fe-4d60d7e0c848.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... send a GET request to get information on a specific item by using itemId from the items table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Update `server/index.js` to ... send a POST request to update the information of a specific item by using itemId from the items table.
- [x] Test with HTTPie

### ⚡ Client Tasks

- [x] Make sure the "Add items" button stays on the top layer and set the href to #add-item.
- [x] Add shadow on an item when user hovers over it.
- [x] Add `handleMouseEnter()` function and handleMouseLeave() function to make it be able to add shadow.
- [x] Add a pen icon on each item.
- [x] Create a new component named `edit-item.jsx`.
  - [x] Import React from 'react'.
  - [x] Add a class `EditItem` to the component.
  - [x] Add constructor and super and this.state.
- [x] Update the renderPage function in `app.jsx` file for a selected item for editing.
- [x] Add `componentDidMount()` function and fetch to send a GET request to "/api/items/:itemId"
- [x] Move `createOptions()` function to a new component called `create-options`.
- [x] Add form in render() function and make sure it's automatically filled the selected item's information
- [x] Update this.state in the `constructor()` to store the information after the item is edited.
- [x] Add handleCategoryChange(), handleBrandChange(), handleColorChange(), handleNotesChange() functions.
- [x] Create handleSubmit() function.
  - [x] Prevent the default form submission behavior
  - [x] Create an Updated formdata object
  - [x] Append entries to the form data object
  - [x] Use fetch to send a POST request to update the specific item.
  - [x] Make sure to set this.state to original status.
- [x] Add a confirmation pop up window.
- [x] Make sure that when the pun icon clicked, it takes to edit view.
- [x] Check that it looks good on both mobile and desktop screens.
- [x] Check that items-view looks good on both mobile and desktop screens.
- [x] Add hover on 'Add Items'button
- [x] Delete bgremoveImage and set originalImage to just image

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
