### ISSUE TITLE
Feature: User can delete an item.

### ISSUE THREAD

**Issue by mioriimai** [mioriimai/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete an item.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

There is a delete button at the left down corner in edit item view. If user clicks the delete button, a pop up window shows up asking if you want to delete the item for sure. By clicking "delete", the item is deleted and it takes to the list of items view.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/54726911/210014889-7400580a-ddb4-4fa3-88e6-ca8e091d414a.png)
![image](https://user-images.githubusercontent.com/54726911/210014906-8c0df859-4db0-4d6d-a57a-3d0588f2e311.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... send a DETELE request to delete the selected item from the items table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] In the `edit-item` component,
  - [x] Add deleteConfirm in the this.state and set it to false.
  - [x] Add a trash icon to the edit item view.
  - [x] Create a new function called `handleDeleteConfirmPopupClick()` function in the `edit-item` component.
    - [x] Set the deleteConfirm to false.
  - [x] Add a confirmation pop up window.
  - [x] Add onclick of handleDeleteConfirmPopup to the trash can icon and the cancel button.
  - [x] Create a new function called `handleDeleteItem()` function.
    - [x] Use fetch to delete an item from the database.
  - [x] Add onlick handleDeleteItem to the delete button and set the href to #items.
  - [x] Make sure selecting delete takes user to items view, means set the href to #items.  
- [x] Check that it looks good on both mobile and desktop screens.
- [x] Create a component to ...
- [x] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
