### ISSUE TITLE
Feature: User can sort the items in a list by category, brand, and color.

### ISSUE THREAD

**Issue by mioriimai** [mioriimai/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sort the items in a list by category, brand, and color.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the a list of items view, user can sort items by category, brand, and color.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/54726911/210015110-37b22063-002c-4bcb-8467-af5633aace65.png)
![image](https://user-images.githubusercontent.com/54726911/210015126-4cb18b6a-f340-48e7-bc91-5846fb1a72df.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...send a GET request to get sorted items.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] In items component...
  - [x] Add drop-down menus for a category.
  - [x] Add drop-down menus for a brand.
  - [x] Add drop-down menus for a color.
  - [x] Make sure that they look good on both mobile and desktop screens.
  - [x] Add sortCategory, sortBrand, and sortColor to the this.state in the constructor.
  - [x] Set the value of select element for categories to this.state.sortCategory.
  - [x] Set the value of select element for brands to this.state.sortBrand.
  - [x] Set the value of select element for colors to this.state.sortColor.
  - [x] Create a new function called`handleSortCategoryChange()` method with one parameter called event.
    - [x] Add this.setState and set sortCategory to event.target.value.
    - [x] Use fetch?
  - [x] Create a new function called `handleSorBrandChange()` method with one parameter called event.
    - [x] Add this.setState and set sortBrand to event.target.value.
  - [x] Create a new function called `handleSortColorChange()` method with one parameter called event.
    - [x] Add this.setState and set sortColor to event.target.value.
  - [x] Add onChange to select elements for category and brand and color.
  - [x] In `handleSortCategoryChange()` method, use fetch to get sorted items from the database.
  - [x] In `handleSortBrandChange()` method, use fetch to get sorted items from the database.
  - [x] In `handleSortColorChange()` method, use fetch to get sorted items from the database.
  - [x] Add reset button.
  - [x] Add  `handleSortReset()` method, and use fetch to get all items and use setState and put data to the value of items.
  - [x] Add onclick to the reset button.
  - [x] Make sure that it looks good on both mobile and desktop screens.
  - [x] Add the text that shows there are no items that match the sort conditions.
  - [x] Make sure that it looks good on both mobile and desktop screens.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
