### ISSUE TITLE
Feature: User can add one of their items to the favorite item list.

### ISSUE THREAD

**Issue by mioriimai** [mioriimai/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add one of their items to the favorite item list.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In the a list of items view, when user mouse over an item, the heart icon shows up and by clicking it, the color of heart changes to pink and the item is added to the favorites.
In the favorites view, user can chose which it shows a list of favorite items or outfits.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/54726911/210015459-c45c362a-d258-46e3-989d-ff947863608b.png)
![image](https://user-images.githubusercontent.com/54726911/210015485-9953c085-1be1-4a76-b7d4-6c934e38de93.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... to send a POST request to update an item's favorite status.
- [x] Test with HTTPie
- [x] Update `server/index.js` to ... to send a GET request to get items'data that has favorite=true.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] In items component...
  - [x] Add a heart icon to each item.
  - [x] Make sure when fetch items information, favorite is also included.
  - [x] Create a new function called `handleFavoritesClick()` method.
  - [x] In the `handleFavoritesClick()` method, use fetch to update the favorites state in the item. If it was true, change it to false(opposite to the previous state).
  - [x]  Add onClick to the icon element.
- [x] Update `renderPage()` in `app.jsx` for favorites view. 
- [x] Create a new component called favorite.
  - [x] Add constructor and set this.state.
  - [x] Fill the `render()` method.
  - [x] Add componentDidMount() and in it, use fetch to get items that have favorite=true.
  - [x] Add handleMouseEnter() method and set itemId to event.target.name.
  - [x] Add handleMouseLeave() method and set itemId to null.
  - [x] Add handleFavoriteClick() method and use fetch to update favorite status of selected item. Alse use fetch to get all items that have favorite=true.
  - [x] Add items and outfits button.
  - [x] Make sure it looks good on both desktop and mobile.
  - [x] Add handleItemsButtonClick() method. 
    - [x] Set showItems to !showItems and showOutfits to !showOutfits.
  - [x] Add handleFavoritesButtonClick() method. 
    - [x] Set showItems to !showItems and showOutfits to !showOutfits.
  - [x] Change each button's style when its this.state is updated.
  
### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
