### ISSUE TITLE
Feature: User can save a set of items as an outfit.

### ISSUE THREAD

**Issue by mioriimai** [mioriimai/final-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save a set of items as an outfit.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

By cliking add outfit in the home view, user can create outfits by chosing items from the list and save them as an outfit. The item user choose shows up in the box and user can drag and put it in any position if it's in the box. To implement drag and drop, use the libraly (https://www.npmjs.com/package/react-rnd). By hovering the items in the box, xmark icon show up for each item and user can delete an item. User also can add note. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/54726911/210016161-ed0e06f2-7d0d-4456-b448-bc16edf0343f.png)
![image](https://user-images.githubusercontent.com/54726911/210016177-420b7c61-ab10-4994-921a-e9cfa37e0c48.png)

![image](https://user-images.githubusercontent.com/54726911/210016133-34ffbd94-a3c7-48c4-b55f-e90fb8cbe0cf.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ... add outfits table and outfitItems table.
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... send a GET request to get the selected Item's information by itemId.
- [x] Update `server/index.js` to ... send a POST request to add outfit with its information.
- [x] Update `server/index.js` to ... send a POST request to add to putfitItems table.
- [x] Test with HTTPie 
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a new component called form-outfit.
- [x] Add a constructor and this.state.
- [x] Update `renderPage()` method in `app.jsx`.
- [x] Fill the render() method with the box for outfit.
- [x] Install react-draggable.
- [x] Make sure react-draggable works and I can move an item in the box.
- [x] Add "Add an item" button.
- [x] Create `handleAddButtonClick()` method and set addItemPopup to true.
- [x] Add onclick to add an item button.
- [x] Create popup window to choose an item to add.
- [x] Add `componentDidMount()` method and use fetch to get items and set the data to items.
- [x] Add `handleMouseEnter()` method to update itemId.
- [x] Add `handleMouseLeave()` method to update itemId.
- [x] Install font awesome.
- [x] Add arrow icon to leave popup window.
- [x] Add handlePopupLeaveClick() method and set addItemPopup to false.
- [x] Make sure items list look good on both desktop and mobile.
- [x] Add handleItemClick() method and see addItemPopup to false. Make itemId to number and use fetch to get the item's image and itemId and userId and push the object to chosenItems array.
- [x] Add onClick to the shadow-wrapper element.
- [x] Install react-rnd.
- [x] Make sure it works fine.
- [x] Add `handleOnDrag()` method and update the delta X and Y of the item.
- [x] Make sure when the item was moved, the delta X and Y is stored in the choseItems.
- [x] Add xmark icon.
- [x] Create `handleDeteleChosenItem()` method.
- [x] Add notes.
- [x] Create `handleNotesChanges()` method.
- [x] Add save button.
- [x] Add save confirmation popup modal.
- [x] Create `handleSaveConfirmPopupClick() `method.
- [x] Make sure they look good on both mobile and desktop.
- [x] Create `handleSubmit()` method and use fetch to post an outfit.
- [x] Up to 10 items restriction.
  - [x] Add light icon.
  - [x] Change the message if the choseItems Array reachs to 10.
- [x] Uninstall draggable.
### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors. (fix form-item preview image position.)
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
