### ISSUE TITLE
Feature: User can view a list of outfits.

### ISSUE THREAD

**Issue by mioriimai** [mioriimai/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of outfits.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

In a list of outfits view, user can see the outfits.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/54726911/210016334-53f99632-4cc8-4c8b-a6bf-20a5efe1e964.png)
![image](https://user-images.githubusercontent.com/54726911/210016355-11dbf407-29de-42b6-af7b-5bdca9d68eae.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ... 
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...to send a GET request to get all outfit data.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a new component called `outfits`.
- [x] Add constructor and this.state with outfits:[] and outfitId: null 
- [x] Update route.path in`app.jsx` for outfits view.
- [x] Add componentDidmount() method.
- [x] Use fetch to get all outfits data with its 
- [x] Fill `render()` method.
- [x] Make sure it looks good on both mobile and desktop.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
